version: '3.3'
services:  
  registry:
    container_name: registry
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
    - ./data:/var/lib/registry    
    networks:
      - network  

  nexus:
    container_name: nexus
    restart: always
    image: sonatype/nexus:oss
    ports:
      - 8081:8081
    networks:
      - network
      
networks:
  network:
    driver: bridge 