version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-hello"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1a2eziwt2f8ne"
s3_prefix = "aws-hello"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

