- name: Install Java 8 using YUM.
  yum:
    name: "{{java.VERSION}}"
    state: latest  
  become: true

- name: Install required jenkins packages
  yum:
    name: "{{ item }}"
  loop: ['wget', 'git', 'python-pip', 'net-tools', 'python3']
- pip:
    name: pip
    extra_args: --upgrade
    
- pip:
    name: setuptools

- name: install aws-sam-cli
  shell: python3 -m pip install aws-sam-cli

# - name: Install SAM AWS
#   pip:
#     name: aws-sam-cli  


- name: Download Jenkins repo yum URL for  
  get_url:
    url: "{{jenkins.repo_URL}}"
    dest: /etc/yum.repos.d/jenkins.repo
  become: true

- name: Import GPG Key
  rpm_key:
    state: present
    key: "{{jenkins.gpg_key}}"

- name: Install service Jenkins from repository
  yum :
    name: jenkins
    state: present
